
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-springboot-4
  description: app 4
  annotations:
    tektonci/build-namespace: my-springboot-4-dev
    janus-idp.io/tekton: my-springboot-4
    argocd/app-name: my-springboot-4-dev
    backstage.io/kubernetes-id: my-springboot-4
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ghrhdh1/my-springboot-4
    quay.io/repository-slug: rhdh1/my-springboot-4
  links:
    - url: https://devspaces.apps.cluster-2tgsr.dynamic.redhatworkshops.io/#https://github.com/ghrhdh1/my-springboot-4
      title: OpenShift Dev Spaces (VS Code editor)
      icon: web
spec:
  type: service
  system: development
  lifecycle: production
  owner: user:default/alexgroom
